#!/bin/bash

factorial() {
  num=$1
  result=1
  while [ $num -gt 1 ]; do
    result=$((result * num))
    num=$((num - 1))
  done
  echo $result
}

read -p "Enter a number: " number
factorial $number
